version: '3'
services:
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend_gerenciamento_uol
      ports:
        - 4200:4200
      depends_on:
        - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_gerenciamento_uol
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_gerenciamento_uol
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    container_name: db_gerenciamento_uol
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql